PREFIX wfn: <http://webofcode.org/wfn/>
PREFIX fn: <http://www.w3.org/2005/xpath-functions#>
SELECT *
{
   BIND( wfn:call(CONCAT(STR(fn:concat),"@http://dbpedia.org/sparql"),"alpha","BETA") as ?res )
} 

