PREFIX wfn: <java:org.webofcode.atzori.>
#PREFIX wfn: <http://webofcode.org/wfn/>
PREFIX fn: <http://www.w3.org/2005/xpath-functions#>
select ?f ?result
{
   BIND(CONCAT(STR(fn:concat),"@http://dbpedia.org/sparql") AS ?f)

   # this will be computed against the dbpedia endpoint 
   BIND( wfn:call(?f,"alpha","beta") AS ?result )
} 

